name: Deploy Cryptonaut Vaults

on:
  push:
    branches:
      - main   # Trigger on pushes to main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor
        run: cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked

      - name: Setup environment
        run: |
          echo "RPC_URL=${{ secrets.RPC_URL }}" >> $GITHUB_ENV
          echo "SOLANA_CLUSTER=${{ secrets.SOLANA_CLUSTER }}" >> $GITHUB_ENV
          echo "WALLET_KEYPAIR=~/.config/solana/id.json" >> $GITHUB_ENV
          mkdir -p ~/.config/solana
          echo "${{ secrets.SOLANA_KEYPAIR }}" > ~/.config/solana/id.json

      - name: Make deploy.sh executable
        run: chmod +x deploy.sh

      - name: Run Deployment
        run: ./deploy.sh
